### ISSUE TITLE
fab build.build 语法报错

### ISSUE THREAD

**Issue by xujianhai** [SohuTech/essay#6]
​(work)bogon:essay_demo snow_young$ ls
MANIFEST.in README   conf    fabfile     setup.py
(work)bogon:essay_demo snow_young$ fab build.build
Traceback (most recent call last):
  File "/Users/snow_young/Desktop/sohu/work/lib/python2.7/site-packages/fabric/main.py", line 658, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/Users/snow_young/Desktop/sohu/work/lib/python2.7/site-packages/fabric/main.py", line 165, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/Users/snow_young/Desktop/sohu/work/bin/essay_demo/fabfile/**init**.py", line 27
    'dev': [''],
        ^
SyntaxError: invalid syntax

**Comment by xujianhai** [comment]
已经解决，是  'dev': [''] 上一行后面的没有加逗号导致的问题，希望修改
